Library-Management-System/Library-Management-System/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Library_Management_System.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Library-Management-System/Library-Management-System/Controllers/BookController.cs
using Library_Management_System.DAO;
using Library_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Transactions;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Data.SqlTypes;

namespace Library_Management_System.Controllers
{
    public class BookController : PadraoController<BookViewModel>
    {
        private readonly AuthorDAO AuthorDAO;
        private readonly CategoryDAO CategoryDAO;

        public BookController()
        {
            DAO = new BookDAO();
            AuthorDAO = new AuthorDAO();
            CategoryDAO = new CategoryDAO();
            ExigeAdmin = false;
        }

        protected override void ValidaDados(BookViewModel model, string operacao)
        {
            base.ValidaDados(model, operacao);

            if (string.IsNullOrEmpty(model.Title))
                ModelState.AddModelError("Title", "Preencha o título.");
            if (string.IsNullOrEmpty(model.ISBN))
                ModelState.AddModelError("ISBN", "Preencha o ISBN.");
            if (model.AuthorId <= 0)
                ModelState.AddModelError("AuthorId", "Informe o código do autor.");
            if (model.CategoryId <= 0)
                ModelState.AddModelError("CategoryId", "Informe o código da categoria.");
            if (model.PublishedYear > DateTime.Now.Year)
                ModelState.AddModelError("PublishedYear", "Ano de publicação inválido!");

            // Imagem obrigatória no Insert
            if (model.Image == null && operacao == "I")
                ModelState.AddModelError("Image", "Escolha uma imagem.");
            if (model.Image != null && model.Image.Length / 1024 / 1024 >= 2)
                ModelState.AddModelError("Image", "Imagem limitada a 2 mb.");
            if (ModelState.IsValid)
            {
                // No Update, buscar imagem salva caso não seja informada
                if (operacao == "A" && model.Image == null)
                {
                    BookViewModel book = DAO.Consulta(model.Id);
                    model.ImageByte = book.ImageByte;
                }
                else
                {
                    model.ImageByte = ConvertImageToByte(model.Image);
                }
            }
        }

        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }

        protected override void PreencheDadosParaView(string Operacao, BookViewModel model)
        {
            base.PreencheDadosParaView(Operacao, model);
            if (Operacao == "I")
                model.PublishedYear = DateTime.Now.Year;

            PreparaListaAutoresParaCombo();
            PreparaListaCategoriasParaCombo();
        }

        private void PreparaListaAutoresParaCombo()
        {
            var autores = AuthorDAO.Listagem();
            List<SelectListItem> listaAutores = new List<SelectListItem>
            {
                new SelectListItem("Selecione um autor...", "0")
            };
            foreach (var autor in autores)
            {
                SelectListItem item = new SelectListItem(autor.Name, autor.Id.ToString());
                listaAutores.Add(item);
            }
            ViewBag.Autores = listaAutores;
        }

        private void PreparaListaCategoriasParaCombo()
        {
            var categorias = CategoryDAO.Listagem();
            List<SelectListItem> listaCategorias = new List<SelectListItem>
            {
                new SelectListItem("Selecione uma categoria...", "0")
            };
            foreach (var categoria in categorias)
            {
                SelectListItem item = new SelectListItem(categoria.Description, categoria.Id.ToString());
                listaCategorias.Add(item);
            }
            ViewBag.Categorias = listaCategorias;
        }

        public IActionResult ExibeConsultaAvancada()
        {
            try
            {
                PreparaListaAutoresParaCombo();
                ViewBag.Autores[0] = new SelectListItem("TODAS", "0");
                PreparaListaCategoriasParaCombo();
                ViewBag.Categorias[0] = new SelectListItem("TODAS", "0");
                return View("ConsultaAvancada");
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.Message));
            }
        }

        public IActionResult ObtemDadosConsultaAvancada(string descricao, int autor, int categoria, int dataInicial, int dataFinal)
        {
            try
            {
                BookDAO bookdao = new BookDAO();
                if (string.IsNullOrEmpty(descricao))
                    descricao = "";
                if (dataInicial == 0)
                    dataInicial = SqlDateTime.MinValue.Value.Year;
                if (dataFinal == 0)
                    dataFinal = SqlDateTime.MaxValue.Value.Year;
                var lista = bookdao.ConsultaAvancada(descricao, autor, categoria, dataInicial, dataFinal);
                return PartialView("pvGridBooks", lista);
            }
            catch (Exception erro)
            {
                return Json(new { erro = true, msg = erro.Message });
            }
        }

    }
}

Library-Management-System/Library-Management-System/Controllers/HomeController.cs
using Library_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Library_Management_System.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Library-Management-System/Library-Management-System/Controllers/LoanController.cs
using Library_Management_System.DAO;
using Library_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Transactions;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.Data.SqlTypes;

namespace Library_Management_System.Controllers
{
    public class LoanController : PadraoController<LoanViewModel> {
        private readonly UserDAO UserDAO;
        private readonly BookDAO BookDAO;

        public LoanController()
        {
            DAO = new LoanDAO();
            UserDAO = new UserDAO();
            BookDAO = new BookDAO();
            ExigeAdmin = false;
        }
        protected override void ValidaDados(LoanViewModel model, string operacao) {
            base.ValidaDados(model, operacao);

            if (model.UserId <= 0)
                ModelState.AddModelError("UserId", "Adicione um Usuário.");

            if (model.BookId <= 0)
                ModelState.AddModelError("BookId", "Adicione um Livro.");

            if (model.LoanDate > DateTime.Now)
                ModelState.AddModelError("LoanDate", "Data de empréstimo inválida!");

            if (model.DueDate < model.LoanDate)
                ModelState.AddModelError("DueDate", "Data de vencimento inválida!");
        }

        protected override void PreencheDadosParaView(string Operacao, LoanViewModel model) {
            base.PreencheDadosParaView(Operacao, model);
            if (Operacao == "I") {
                model.LoanDate = DateTime.Now;
                model.DueDate = model.LoanDate.AddDays(7);
            }
            else if (Operacao == "A") {
                model.ReturnDate = DateTime.Now;
            }

            PreparaListaUsuariosParaCombo();
            PreparaListaLivrosParaCombo();
        }

        private void PreparaListaUsuariosParaCombo() {
            var usuarios = UserDAO.Listagem();
            List<SelectListItem> listaUsuarios = new List<SelectListItem>
            {
                new SelectListItem("Selecione um usuário...", "0")
            };
            foreach (var usuario in usuarios) {
                SelectListItem item = new SelectListItem(usuario.Name, usuario.Id.ToString());
                listaUsuarios.Add(item);
            }
            ViewBag.Usuarios = listaUsuarios;
        }

        private void PreparaListaLivrosParaCombo() {
            var livros = BookDAO.Listagem();
            List<SelectListItem> listaLivros = new List<SelectListItem>
            {
                new SelectListItem("Selecione um livros...", "0")
            };
            foreach (var livro in livros) {
                SelectListItem item = new SelectListItem(livro.Title, livro.Id.ToString());
                listaLivros.Add(item);
            }
            ViewBag.Livros = listaLivros;
        }

        public override IActionResult Index()
        {
            if (!HelperController.VerificaAdmin(HttpContext.Session))
            {
                try
                {
                    string userId = HttpContext.Session.GetString("UserId");
                    LoanDAO loandao = new LoanDAO();
                    var lista = loandao.ConsultaEmprestimos(userId);
                    return View(NomeViewIndex, lista);
                }
                catch (Exception erro)
                {
                    return View("Error", new ErrorViewModel(erro.ToString()));
                }
            }
            else
            {
                return base.Index();
            }
        }

        public IActionResult ExibeConsultaAvancada()
        {
            try
            {
                return View("ConsultaAvancada");
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.Message));
            }
        }

        public IActionResult ObtemDadosConsultaAvancada(string usuario, string descricao, DateTime dataInicial, DateTime dataFinal)
        {
            try
            {
                LoanDAO loandao = new LoanDAO();
                if (string.IsNullOrEmpty(usuario))
                    usuario = "";
                if (string.IsNullOrEmpty(descricao))
                    descricao = "";
                if (dataInicial.Date == Convert.ToDateTime("01/01/0001"))
                    dataInicial = SqlDateTime.MinValue.Value;
                if (dataFinal.Date == Convert.ToDateTime("01/01/0001"))
                    dataFinal = SqlDateTime.MaxValue.Value;
                if (!HelperController.VerificaAdmin(HttpContext.Session))
                {
                    string userId = HttpContext.Session.GetString("UserId");
                    UserDAO userdao = new UserDAO();
                    var userData = userdao.Consulta(Convert.ToInt32(userId));
                    usuario = userData.Name;
                }
                var lista = loandao.ConsultaAvancada(usuario, descricao, dataInicial, dataFinal);
                return PartialView("pvGridLoans", lista);
            }
            catch (Exception erro)
            {
                return Json(new { erro = true, msg = erro.Message });
            }
        }
    }
}

Library-Management-System/Library-Management-System/Controllers/UserController.cs
using Library_Management_System.DAO;
using Library_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text.RegularExpressions;

namespace Library_Management_System.Controllers
{
    public class UserController : PadraoController<UserViewModel> {
        public UserController()
        {
            DAO = new UserDAO();
            NovoUsuario = true;
        }

        protected override void ValidaDados(UserViewModel model, string operacao) {
            base.ValidaDados(model, operacao);

            if (string.IsNullOrEmpty(model.Name))
                ModelState.AddModelError("Name", "Preencha o nome.");

            if (string.IsNullOrEmpty(model.Email))
                ModelState.AddModelError("Email", "Preencha o Email.");
            else if (!Regex.IsMatch(model.Email, @"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"))
            {
                ModelState.AddModelError("Email", "Por favor, insira um endereço de e-mail válido.");
            }

            if (string.IsNullOrEmpty(model.Password))
                ModelState.AddModelError("Password", "Adicione uma senha.");
        }

        protected override void PreencheDadosParaView(string Operacao, UserViewModel model) { 
            if(Operacao == "I") {
                model.RegistrationDate = DateTime.Now;
            }
        }
    }
}

Library-Management-System/Library-Management-System/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewData["Title"] = "Home";
}
<p class="text-3xl font-bold text-center mt-4">Sistema de Gerenciamento de Biblioteca</p>

<div>
    @{
        if (Context.Session.GetString("Logado") == "true")
        {
            <div class="container mx-auto px-4 py-8 flex flex-wrap justify-center">
                <div class="w-full sm:w-1/2 lg:w-1/3 p-2">
                    <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                        <a asp-controller="Book" asp-action="Index">
                            <div class="p-6">
                                <h2 class="text-2xl font-bold mb-2">Livros</h2>
                                <p>Gerencie os livros da biblioteca.</p>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="w-full sm:w-1/2 lg:w-1/3 p-2">
                    <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                        <a asp-controller="Loan" asp-action="Index">
                            <div class="p-6">
                                <h2 class="text-2xl font-bold mb-2">Empréstimos</h2>
                                <p>Gerencie os empréstimos de livros.</p>
                            </div>
                        </a>
                    </div>
                </div>
                @if (Context.Session.GetString("Admin") == "true")
                {
                    <div class="w-full sm:w-1/2 lg:w-1/3 p-2">
                        <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                            <a asp-controller="Author" asp-action="Index">
                                <div class="p-6">
                                    <h2 class="text-2xl font-bold mb-2">Autores</h2>
                                    <p>Gerencie os autores dos livros.</p>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="w-full sm:w-1/2 lg:w-1/3 p-2">
                        <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                            <a asp-controller="Category" asp-action="Index">
                                <div class="p-6">
                                    <h2 class="text-2xl font-bold mb-2">Categorias</h2>
                                    <p>Gerencie as categorias dos livros.</p>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="w-full sm:w-1/2 lg:w-1/3 p-2">
                        <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                            <a asp-controller="User" asp-action="Index">
                                <div class="p-6">
                                    <h2 class="text-2xl font-bold mb-2">Usuários</h2>
                                    <p>Gerencie os usuários do sistema.</p>
                                </div>
                            </a>
                        </div>
                    </div>
                }
            </div>
        }
        else
        {
            <div class="container w-4/6 mx-auto px-4 pt-12 py-4">
                <div class="bg-white shadow-lg rounded-lg overflow-hidden p-6 mb-8">
                    <h2 class="text-xl font-bold mb-2">Bem-vindo ao Sistema de Gerenciamento de Biblioteca!</h2>
                    <p class="text-gray-700">Esta aplicação foi desenvolvida para ajudar a organizar e gerenciar as operações diárias de uma biblioteca, fornecendo um conjunto completo de ferramentas para gerenciar livros, empréstimos, autores, categorias e usuários. Se você é um administrador, pode acessar funcionalidades adicionais, como o gerenciamento de autores, categorias e usuários do sistema.</p>
                    <a href="@Url.Action("Index", "About")" class="bg-gray-700 hover:bg-gray-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-4 inline-block">Saiba mais</a>
                </div>
            </div>
            <div class="container mx-auto w-full sm:w-1/2 lg:w-1/3">
                <div class="bg-white shadow-lg rounded-lg overflow-hidden p-6">
                    <h2 class="text-xl font-bold mb-2">Acesso Restrito</h2>
                    <p class="text-gray-700">Faça login para acessar o sistema e suas funcionalidades. Se você não tem uma conta, registre-se para obter acesso.</p>
                    <a href="@Url.Action("Index", "Login")" class="bg-gray-700 hover:bg-gray-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-4 inline-block">Área de Login</a>
                </div>
            </div>
        }
    }
</div>